// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AgentRoster.tsx": () => import("../components/mockups/AgentRoster.tsx"),
  "./components/mockups/BudgetDashboard.tsx": () => import("../components/mockups/BudgetDashboard.tsx"),
  "./components/mockups/CompanyDashboard.tsx": () => import("../components/mockups/CompanyDashboard.tsx"),
  "./components/mockups/GoalsTree.tsx": () => import("../components/mockups/GoalsTree.tsx"),
  "./components/mockups/GovernanceQueue.tsx": () => import("../components/mockups/GovernanceQueue.tsx"),
  "./components/mockups/HeartbeatPanel.tsx": () => import("../components/mockups/HeartbeatPanel.tsx"),
  "./components/mockups/OrchestrationHQ.tsx": () => import("../components/mockups/OrchestrationHQ.tsx"),
  "./components/mockups/OrgChart.tsx": () => import("../components/mockups/OrgChart.tsx"),
  "./components/mockups/Shell.tsx": () => import("../components/mockups/Shell.tsx"),
  "./components/mockups/SwarmControl.tsx": () => import("../components/mockups/SwarmControl.tsx"),
  "./components/mockups/TaskBoard.tsx": () => import("../components/mockups/TaskBoard.tsx")
};
